"""Lookup tables shared by the golden model, the C++ header and the RTL ROMs.

Definitions (docs/NUMERICS.md):
  SIG[j]  = round(sigmoid(-8 + j/16) * 65536), j = 0..256     (u16, 65514 at j=256)
  EXPI[i] = round(exp(-i) * 65535),           i = 0..15        (u16)
  EXPF[f] = round(exp(-f/256) * 65535),       f = 0..255       (u16)
Rounding: Python round-half-even on exact doubles — the tables are generated once and
committed as text, so all consumers read identical constants.
"""
from __future__ import annotations

import math
from pathlib import Path

import numpy as np


def sigmoid_lut() -> np.ndarray:
    xs = [-8.0 + j / 16.0 for j in range(257)]
    vals = [min(65535, round(65536.0 / (1.0 + math.exp(-x)))) for x in xs]
    return np.array(vals, dtype=np.uint16)


def exp_int_lut() -> np.ndarray:
    return np.array([round(math.exp(-i) * 65535) for i in range(16)], dtype=np.uint16)


def exp_frac_lut() -> np.ndarray:
    return np.array([round(math.exp(-f / 256.0) * 65535) for f in range(256)], dtype=np.uint16)


def _fmt_rows(vals, per_row=16):
    rows = []
    for i in range(0, len(vals), per_row):
        rows.append(", ".join(f"{int(v):5d}" for v in vals[i : i + per_row]))
    return rows


def write_cpp_header(path: Path) -> None:
    sig, ei, ef = sigmoid_lut(), exp_int_lut(), exp_frac_lut()
    out = ["// GENERATED by python/llaccel/luts.py — do not edit.", "#pragma once", "#include <array>", "#include <cstdint>", "",
           "namespace llaccel::num {", ""]
    for name, arr in (("kSigmoidLut", sig), ("kExpIntLut", ei), ("kExpFracLut", ef)):
        out.append(f"inline constexpr std::array<uint16_t, {len(arr)}> {name} = {{")
        out += ["    " + r + "," for r in _fmt_rows(arr)]
        out.append("};")
        out.append("")
    out.append("}  // namespace llaccel::num")
    path.write_text("\n".join(out) + "\n")


def write_sv_header(path: Path) -> None:
    sig, ei, ef = sigmoid_lut(), exp_int_lut(), exp_frac_lut()
    out = ["// GENERATED by python/llaccel/luts.py — do not edit.", "`ifndef LLACCEL_LUTS_SVH", "`define LLACCEL_LUTS_SVH", ""]
    for name, arr in (("SIGMOID_LUT", sig), ("EXP_INT_LUT", ei), ("EXP_FRAC_LUT", ef)):
        out.append(f"localparam logic [15:0] {name} [{len(arr)}] = '{{")
        rows = _fmt_rows(arr)
        body = ",\n".join("    " + r.replace(", ", ", ").replace("  ", " ") for r in rows)
        # SystemVerilog needs 16'd prefixes
        body = ",\n".join("    " + ", ".join(f"16'd{int(v)}" for v in arr[i:i+16]) for i in range(0, len(arr), 16))
        out.append(body)
        out.append("};")
        out.append("")
    out.append("`endif")
    path.write_text("\n".join(out) + "\n")


def main() -> None:
    root = Path(__file__).resolve().parents[2]
    write_cpp_header(root / "include" / "llaccel" / "luts.h")
    write_sv_header(root / "rtl" / "llaccel_luts.svh")
    print("wrote luts.h and llaccel_luts.svh")


if __name__ == "__main__":
    main()
